/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld/HelloWorld.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PageHeader: typeof import('./src/components/layout/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const HelloWorld: typeof import('./src/components/HelloWorld/HelloWorld.vue')['default']
  const MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
  const NAlert: typeof import('naive-ui')['NAlert']
  const NButton: typeof import('naive-ui')['NButton']
  const NEmpty: typeof import('naive-ui')['NEmpty']
  const NInput: typeof import('naive-ui')['NInput']
  const NInputGroup: typeof import('naive-ui')['NInputGroup']
  const NInputNumber: typeof import('naive-ui')['NInputNumber']
  const NPopconfirm: typeof import('naive-ui')['NPopconfirm']
  const NPopover: typeof import('naive-ui')['NPopover']
  const NRadioButton: typeof import('naive-ui')['NRadioButton']
  const NRadioGroup: typeof import('naive-ui')['NRadioGroup']
  const NSelect: typeof import('naive-ui')['NSelect']
  const NSpin: typeof import('naive-ui')['NSpin']
  const NSwitch: typeof import('naive-ui')['NSwitch']
  const NTag: typeof import('naive-ui')['NTag']
  const NText: typeof import('naive-ui')['NText']
  const NTooltip: typeof import('naive-ui')['NTooltip']
  const PageHeader: typeof import('./src/components/layout/PageHeader.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}